option_settings:
  - namespace: aws:elasticbeanstalk:container:nodejs:staticfiles
    option_name: /public
    value: /public
  - option_name: RACK_ENV
    value: production
commands:
  - scheduler: "rake environment resque:scheduler"
  - worker: QUEUE=date_queue rake environment resque:work"
  - cwd: "/var/app/current"
