option_settings:
  - namespace: aws:elasticbeanstalk:container:nodejs:staticfiles
    option_name: /public
    value: /public
  - option_name: RACK_ENV
    value: production
container_commands:
  scheduler:
    command: "BACKGROUND=yes rake environment resque:scheduler"
    cwd: "/var/app/current"
  worker:
    command: "BACKGROUND=yes QUEUE=date_queue rake environment resque:work"
    cwd: "/var/app/current"
