queue_emails:
  cron: "*/5 * * * *"
  class: "CheckExpirationDate"
  args:
  queue: date_queue
  description: "This job will check if user_products are going to expire and then send users email reminders"
