# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 366929e4c7a3360559faf5c2b87aa1c3ddc8d624e9e55f7d2e74090d2d465759bb5cad6ca811aeb97faaa3e2fd957b248e19a02164624299983dab59ff119d38

test:
  secret_key_base: b74cfc8f6b6cef10c845f98f1e5e78750be94db7031615bbbf67d1e13b3b1e81b4e59b31b3b1ec1389da360765cc0e8f90e0275bed526f21de121802fe049aba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
